In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score

# Step 1: Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Step 2: Introduce artificial missing values (for learning)
X[0][0] = np.nan
X[10][2] = np.nan

# Step 3: Handle missing values (Imputation)
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)

# Step 4: Feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Step 5: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# Step 6: Logistic Regression (multi-class)
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Step 7: Predictions
y_pred = model.predict(X_test)

# Step 8: Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Step 9: Parameters
print("\nWeights:\n", model.coef_)
print("\nBias:\n", model.intercept_)

Accuracy: 1.0

Weights:
 [[-0.93969174  1.05712811 -1.76464811 -1.61312679]
 [ 0.46525492 -0.36729152 -0.28784143 -0.66561393]
 [ 0.47443682 -0.68983659  2.05248955  2.27874073]]

Bias:
 [-0.30168343  1.81121208 -1.50952865]
